---
- name: Undeploy task to remove
  uri:
    url: https://localhost:8443/org.talend.administrator/metaServlet?{{ ( '{' +
      '"authUser":"' + api_admin_user + '","authPass":"' + api_admin_pass + '",' +
      '"actionName":"requestUndeployEsbTask"' + ',"taskId":' + item.existing_task_id|string +
      '}' ) | b64encode }}
    return_content: true
    validate_certs: false
    status_code: 200
    timeout: 300
  register: undeploy_task
  # This is temporary nexus fix until artifactory supported ... missing xml and zookeeper features on reposistory but still works
  # failed_when: undeploy_task.json.returnCode is not defined or undeploy_task.json.returnCode != 0
  failed_when: undeploy_task.json.returnCode is not defined or undeploy_task.json.returnCode != 170

- name: Delete task to remove
  uri:
    url: https://localhost:8443/org.talend.administrator/metaServlet?{{ ( '{' +
      '"authUser":"' + api_admin_user + '","authPass":"' + api_admin_pass + '",' +
      '"actionName":"deleteEsbTask"' + ',"taskId":' + item.existing_task_id|string +
      '}' ) | b64encode }}
    return_content: true
    validate_certs: false
    status_code: 200
    timeout: 300
  register: delete_task
  failed_when: delete_task.json.returnCode is not defined or delete_task.json.returnCode != 0

- name: Add new task
  uri:
    url: https://localhost:8443/org.talend.administrator/metaServlet?{{ ( '{' +
      '"authUser":"' + api_admin_user + '","authPass":"' + api_admin_pass + '",' +
      '"actionName":"saveEsbTask"' + ',"taskName":"' + item.task.name + '",' +
      '"repository":"' + deploy_task_repository + '","featureUrl":"' + item.task.url_prefix + item.task.version + item.task.url_suffix + '",' +
      '"featureName":"' + item.task.feature_name + '","featureVersion":"' + item.task.version + '",' +
      '"featureType":"' + item.task.type + '","runtimeContext":"' + deploy_task_context + '",' +
      '"runtimeServerName":"' + deploy_task_server + '","runtimePropertyId":"' + item.task.pid + '"' +
      '}' ) | b64encode }}
    return_content: true
    validate_certs: false
    status_code: 200
    timeout: 300
  register: add_new_task
  failed_when: add_new_task.json.returnCode is not defined or add_new_task.json.returnCode != 0

- name: Deploy new task
  uri:
    url: https://localhost:8443/org.talend.administrator/metaServlet?{{ ( '{' +
      '"authUser":"' + api_admin_user + '","authPass":"' + api_admin_pass + '",' +
      '"actionName":"requestDeployEsbTask"' + ',"taskId":' + add_new_task.json.taskId|string +
      '}' ) | b64encode }}
    return_content: true
    validate_certs: false
    status_code: 200
    timeout: 300
  register: deploy_new_task
  failed_when: deploy_new_task.json.returnCode is not defined or deploy_new_task.json.returnCode != 0
