---
grubconf: /etc/grub.conf
fstab: /etc/fstab
mailconfig: /etc/exim/exim.conf

syslog_server: "{{ '10.183.195.60' if ansible_domain == 'akait.local' else '10.167.195.60' }}"
puppet_server: "{{ 'puppet.akait.local' if ansible_domain == 'akait.local' else 'puppetpp.akaitpp.local' if ansible_domain == 'akaitpp.local' else 'akaittd.local'}}"
ntp_server: "{{ 'a-p-ntp-01' if ansible_domain == 'akait.local' else 'a-o-ntp-01' if ansible_domain == 'akaitpp.local' else 'a-t-ntp-01'}}"
sudoers_file: "{{ '/etc/sudoers.d/10_qualy' if ansible_domain == 'akaittd.local' else '/etc/opt/quest/qpm4u/policy/sudoers'}}"
# latest patchset
wp_patch_level: '20170127-0'
