---
- name: Check for a previously modified config file
  lineinfile:
    path: "{{ talend_app_conf_path }}/configuration.properties"
    line: "# BEGIN ANSIBLE MANAGED BLOCK"
    state: present
  check_mode: true
  register: config_modified

- name: stop talend-tac # noqa: no-handler
  service:
    name: "talend-tac-{{ talend_version }}"
    state: stopped
  when: config_modified is changed

- name: Apply config that is persisted to database which will get removed from file once processed # noqa: no-handler
  blockinfile:
    path: "{{ talend_app_conf_path }}/configuration.properties"
    block: |
      amc.serverlocationurl=https://{{ tac_lb_host }}/amc
      businessLog.path={{ talend_logs_path }}/business.log
      log4j.path.talendAppender={{ talend_logs_path }}/technical.log
      scheduler.conf.archivesJobsRootPath={{ shared_jobs_path }}
      scheduler.conf.jobExecutionLogs.rootPath={{ shared_logs_path }}
      useLDAPAuthentication=true      
      enableLDAPS=true
      ldapServerIp={{ ldap_host }}
      ldapServerPort=636
      ldapPrincipalDNPrefix={{ ldap_default_full_dn_var }}
      ldapAdminPassword={{ ldap_default_password }}
      ldap.fields.login=sAMAccountName
      ldap.fields.mail=mail
      ldap.fields.firstname=givenName
      ldap.fields.lastname=sn
      useLDAPLoginPwd=true
      scheduler.conf.repo.type=Artifactory
      scheduler.conf.artifactory.url={{ artifactory_url }}
      scheduler.conf.artifactory.username={{ artifactory_user }}
      scheduler.conf.artifactory.password={{ artifactory_pass }}
      scheduler.conf.artifactory.defaultRepoRelease={{ releases_repo }}
      scheduler.conf.artifactory.defaultRepoSnapshot={{ snapshots_repo }}
      scheduler.conf.artifactory.defaultGroupID=org.example
      libraries.conf.repo.type=Artifactory
      artifactory.libLocationUrl={{ artifactory_url }}
      artifactory.libUsername={{ artifactory_user }}
      artifactory.libPassword={{ artifactory_pass }}
      artifactory.repository.releases={{ releases_repo }}
      artifactory.repository.snapshots={{ snapshots_repo }}
  when: config_modified is changed

- name: start talend-tac # noqa: no-handler
  service:
    name: "talend-tac-{{ talend_version }}"
    state: started
  when: config_modified is changed

- name: Wait for API to become available
  uri:
    url: https://localhost:8443/org.talend.administrator/metaServlet?{{ ( '{' +
      '"actionName":"help"' +
      '}' ) | b64encode }}
    return_content: true
    validate_certs: false
  register: this
  until: this.status == 200 and this.json.returnCode is defined and this.json.returnCode == 0
  retries: 15
  delay: 10
