---
- name: Fetch admin Engineers from LDAP # noqa: risky-shell-pipe
  shell: |
    ldapsearch -x -H ldap://{{ ldap_host }}:389 -D "{{ ldap_default_bind_dn_var }}" -w "{{ ldap_default_password }}" -b "DC=columbus,DC=local"  "memberOf=CN={{ item }},OU=Groups,OU=Administrative,DC=columbus,DC=local" distinguishedName | awk -F ': '  '/dn/{printf $2 "|"}'
  with_items: "{{ engineers_ldap_groups }}"
  register: ldap_users
  tags:
    - add_ldap_users

- name: set fact
  set_fact:
    admin_users: "{{ ldap_users.results | map(attribute='stdout')| join }}"
  tags:
    - add_ldap_users

- name: List existing users
  uri:
    url: https://localhost:8443/org.talend.administrator/metaServlet?{{ ( '{' +
      '"authUser":"' + sec_admin_user + '","authPass":"' + sec_admin_pass + '",' +
      '"actionName":"listUsers","type":"DQ"' +
      '}' ) | b64encode }}
    return_content: true
    validate_certs: false
    status_code: 200
    timeout: 300
  register: existing_users
  failed_when: existing_users.json.returnCode is not defined or existing_users.json.returnCode != 0
  tags:
    - add_ldap_users

- name: Add ldap admin user
  uri:
    url: https://localhost:8443/org.talend.administrator/metaServlet?{{ ( '{' +
      '"authUser":"' + sec_admin_user + '","authPass":"' + sec_admin_pass + '",' +
      '"actionName":"createUser","active":true,"userType":"DQ",' +
      '"userDn":"' + item + '",' +
      '"userRole":["Administrator","Operation manager","Viewer","Designer"]' +
      '}' ) | b64encode }}
    validate_certs: false
    return_content: true
    status_code: 200
    timeout: 300
  register: this
  with_items: "{{ admin_users[:-1].split('|') }}"
  when: existing_users.content.find('"ldapId":"' + item + '"') == -1 and add_admin_users_to_tac == "true"
  failed_when: this.json.returnCode is not defined or this.json.returnCode != 0
  tags:
    - add_ldap_users
